# Generated by Django 2.2.6 on 2020-01-16 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1000)),
                ('slug', models.SlugField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default='')),
                ('category', models.CharField(choices=[('Technology', 'Technology'), ('Travel', 'Travel'), ('Sports', 'Sports'), ('News', 'News'), ('Music', 'Music'), ('Work', 'Work')], default='', max_length=200)),
                ('cover', models.FileField(default='', upload_to='')),
                ('cover2', models.FileField(default='', upload_to='')),
                ('large_heading', models.CharField(default='', max_length=500)),
                ('large_heading_text', models.CharField(default='', max_length=50000)),
                ('quote', models.CharField(default='', max_length=500)),
                ('quotes_name', models.CharField(default='', max_length=500)),
                ('smaller_heading', models.CharField(default='', max_length=5000)),
                ('smaller_heading_text', models.CharField(default='', max_length=5000)),
                ('tag1', models.CharField(default='', max_length=500)),
                ('tag2', models.CharField(default='', max_length=500)),
                ('tag3', models.CharField(default='', max_length=500)),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
