# Generated by Django 2.2.6 on 2020-01-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='cover',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
