# Generated by Django 2.2.6 on 2020-01-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200116_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(default='', upload_to='images/')),
                ('title', models.CharField(max_length=2000)),
                ('about_me', models.CharField(max_length=1000)),
                ('where_to_find', models.CharField(max_length=1000)),
                ('find_1', models.CharField(max_length=1000)),
                ('find_2', models.CharField(max_length=1000)),
                ('find_3', models.CharField(max_length=1000)),
                ('contact_info', models.CharField(max_length=1000)),
                ('gmail', models.CharField(max_length=1000)),
                ('insta', models.CharField(max_length=1000)),
                ('youtube', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=1000)),
            ],
        ),
    ]
